root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main ./cmd/main.go" # Укажите путь к вашей main.go
  bin = "tmp/main"
  delay = 1000
  exclude_dir = ["tmp", "vendor"]
  exclude_regex = ["_test.go"]
  include_ext = ["go"]
  log = "air.log"

[log]
  time = false
